-- =============================================================
-- iLEAD Project Management — Supabase Schema (Sprint 1)
-- Run this in Supabase SQL Editor: Dashboard → SQL Editor → New Query
--
-- IMPORTANT: This is a FRESH INSTALL script.
-- If you have existing data, use migration_notes below first.
--
-- Migration notes for existing deployments:
--   1. Export current data via CSV (app Export button)
--   2. Run this script on a NEW Supabase project
--   3. Re-import data with UUIDs generated by the seed or import tool
-- =============================================================

-- Enable UUID generation (built into Supabase by default)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================
-- DROP existing tables safely (order matters — children first)
-- =============================================================
DROP TABLE IF EXISTS tasks       CASCADE;
DROP TABLE IF EXISTS activities  CASCADE;
DROP TABLE IF EXISTS projects    CASCADE;
DROP TABLE IF EXISTS partners    CASCADE;

-- =============================================================
-- PARTNERS
-- =============================================================
CREATE TABLE partners (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       TEXT        NOT NULL,
  color      TEXT,
  sector     TEXT,
  region     TEXT,
  author     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- PROJECTS
-- =============================================================
CREATE TABLE projects (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "partnerId"  UUID        NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  name         TEXT        NOT NULL,
  status       TEXT        NOT NULL DEFAULT 'not_started'
                           CHECK (status IN ('not_started','in_progress','done','not_completed')),
  "subCode"    TEXT,
  "startDate"  DATE,
  "endDate"    DATE,
  pos          BIGINT      NOT NULL DEFAULT 0,
  description  TEXT,
  author       TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Prevent endDate < startDate
  CONSTRAINT chk_project_dates
    CHECK ("startDate" IS NULL OR "endDate" IS NULL OR "startDate" <= "endDate")
);

-- =============================================================
-- ACTIVITIES
-- =============================================================
CREATE TABLE activities (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "projectId"   UUID        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'not_started'
                            CHECK (status IN ('not_started','in_progress','done','not_completed')),
  stage         TEXT        DEFAULT 'S1'
                            CHECK (stage IN ('S1','S2','S3','S4','S5','S6','S7')),
  "ballOwner"   TEXT,
  ca            TEXT,
  type          TEXT        CHECK (type IN (NULL,'local','in-country','virtual')),
  "subCode"     TEXT,
  "startDate"   DATE,
  "endDate"     DATE,
  "nextAction"  TEXT,
  notes         TEXT,
  pos           BIGINT      NOT NULL DEFAULT 0,
  author        TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Prevent endDate < startDate
  CONSTRAINT chk_activity_dates
    CHECK ("startDate" IS NULL OR "endDate" IS NULL OR "startDate" <= "endDate")
);

-- =============================================================
-- TASKS
-- =============================================================
CREATE TABLE tasks (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "activityId"  UUID        NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
  name          TEXT        NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'todo'
                            CHECK (status IN ('todo','in_progress','done')),
  assignee      TEXT,
  "dueDate"     DATE,
  notes         TEXT,
  pos           BIGINT      NOT NULL DEFAULT 0,
  author        TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- INDEXES on foreign keys (critical for reverse lookups)
-- e.g. Task → Activity → Project → Partner
-- =============================================================
CREATE INDEX idx_projects_partner_id   ON projects("partnerId");
CREATE INDEX idx_activities_project_id ON activities("projectId");
CREATE INDEX idx_tasks_activity_id     ON tasks("activityId");

-- Extra indexes for common filter/sort patterns
CREATE INDEX idx_activities_status    ON activities(status);
CREATE INDEX idx_activities_end_date  ON activities("endDate");
CREATE INDEX idx_tasks_status         ON tasks(status);
CREATE INDEX idx_tasks_due_date       ON tasks("dueDate");

-- =============================================================
-- AUTO-UPDATE updated_at TRIGGER
-- =============================================================
CREATE OR REPLACE FUNCTION _update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_partners_updated_at
  BEFORE UPDATE ON partners
  FOR EACH ROW EXECUTE FUNCTION _update_updated_at();

CREATE TRIGGER trg_projects_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW EXECUTE FUNCTION _update_updated_at();

CREATE TRIGGER trg_activities_updated_at
  BEFORE UPDATE ON activities
  FOR EACH ROW EXECUTE FUNCTION _update_updated_at();

CREATE TRIGGER trg_tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION _update_updated_at();

-- =============================================================
-- ROW LEVEL SECURITY (RLS)
--
-- PHASE A — Current state (no auth system yet):
--   anon can read + write. Protects against accidental public exposure
--   while allowing the app to function without login.
--
-- PHASE B — After adding Supabase Auth (Sprint 5):
--   Comment out Phase A policies, uncomment Phase B policies.
--   Only authenticated users will be able to write data.
-- =============================================================
ALTER TABLE partners   ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects   ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks      ENABLE ROW LEVEL SECURITY;

-- ── PHASE A: Open read/write for anon (current app — no login) ──
CREATE POLICY "anon_select"  ON partners   FOR SELECT USING (true);
CREATE POLICY "anon_insert"  ON partners   FOR INSERT WITH CHECK (true);
CREATE POLICY "anon_update"  ON partners   FOR UPDATE USING (true);
CREATE POLICY "anon_delete"  ON partners   FOR DELETE USING (true);

CREATE POLICY "anon_select"  ON projects   FOR SELECT USING (true);
CREATE POLICY "anon_insert"  ON projects   FOR INSERT WITH CHECK (true);
CREATE POLICY "anon_update"  ON projects   FOR UPDATE USING (true);
CREATE POLICY "anon_delete"  ON projects   FOR DELETE USING (true);

CREATE POLICY "anon_select"  ON activities FOR SELECT USING (true);
CREATE POLICY "anon_insert"  ON activities FOR INSERT WITH CHECK (true);
CREATE POLICY "anon_update"  ON activities FOR UPDATE USING (true);
CREATE POLICY "anon_delete"  ON activities FOR DELETE USING (true);

CREATE POLICY "anon_select"  ON tasks      FOR SELECT USING (true);
CREATE POLICY "anon_insert"  ON tasks      FOR INSERT WITH CHECK (true);
CREATE POLICY "anon_update"  ON tasks      FOR UPDATE USING (true);
CREATE POLICY "anon_delete"  ON tasks      FOR DELETE USING (true);

-- ── PHASE B: Restrict writes to authenticated users (Sprint 5) ──
-- (Drop Phase A policies and uncomment below when auth is added)
--
-- CREATE POLICY "auth_select"  ON partners FOR SELECT USING (true);
-- CREATE POLICY "auth_insert"  ON partners FOR INSERT TO authenticated WITH CHECK (true);
-- CREATE POLICY "auth_update"  ON partners FOR UPDATE TO authenticated USING (true);
-- CREATE POLICY "auth_delete"  ON partners FOR DELETE TO authenticated USING (true);
-- (repeat for projects, activities, tasks)

-- =============================================================
-- VERIFY
-- =============================================================
SELECT 'Schema created successfully' AS status;
